name: Build Manifest for CCS Starterpack

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
    paths:
      - "build-manifest.py" # Run if the logic changes
    paths-ignore:
      - ".github/workflows/build-manifest.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Explicitly give the bot write access

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run build manifest
        run: python build-manifest.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          # The diff check prevents the action from failing if nothing changed
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: update build manifest" && git push origin HEAD:${{ github.ref_name }})
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
